# Cross-Compilation Support Module
#
# Aggregates platform-specific cross-compilation support and provides
# common shell utilities for working with cross-compilation targets.
#
# Configuration:
#   shell.crossPlatforms - Function selecting which cross targets to support
#                          e.g., `ps: with ps; [ wasi32 ghcjs ]`
#
# The per-target wrapper scripts (`wasm32-unknown-wasi ghc --version`) are
# generated by each driver rather than here, since they are built from the
# driver's own cross compilers.

{ config, lib, pkgs, ... }:

let crossPlatformSet = lib.genAttrs (builtins.attrNames pkgs.pkgsCross) (name: name);
    selectedCrossPlatforms = config.shell.crossPlatforms crossPlatformSet;
    targetPrefixes =
      let prefixes = lib.filter (p: p != "") (map (name:
            pkgs.pkgsCross.${name}.stdenv.hostPlatform.config
          ) selectedCrossPlatforms);
      in prefixes ++ lib.optional (builtins.any (p: lib.hasInfix "wasm" p) prefixes) "wasm";

in {

  # Platform-specific cross-compilation support modules
  imports = [
    ./ghcjs  # JavaScript/GHCJS target support
    ./wasm   # WebAssembly/WASM target support
  ];

  # A shell that selects cross targets carries both native and cross-compiled
  # dependencies, so NIX_LDFLAGS names library directories for both. Handing a
  # native shared object to a cross linker fails on the file type, and the
  # reverse fails just as well, so each side gets only its own: the paths of
  # every selected target are dropped here, and a cross wrapper keeps only
  # those. The unfiltered values stay in the environment for the wrappers to
  # start from.
  shell.shellHook = lib.mkIf (selectedCrossPlatforms != []) (
    let prefixPattern = lib.concatMapStringsSep "|" (p: "*${p}*") targetPrefixes;
    in ''
      _filter_native_ldflags() {
        local result=""
        for arg in $1; do
          if [[ "$arg" == -L* ]]; then
            case "$arg" in
              ${prefixPattern}) ;;
              *) result="$result $arg" ;;
            esac
          else
            result="$result $arg"
          fi
        done
        echo "$result"
      }

      # Capture the unfiltered flags only once. Re-evaluating the hook in the
      # same shell must not overwrite them with the already-filtered values, or
      # the wrapper below ends up filtering a filtered list and keeps nothing.
      # `-` rather than `:-`, so a genuinely empty capture is preserved.
      export NIX_LDFLAGS_UNFILTERED="''${NIX_LDFLAGS_UNFILTERED-$NIX_LDFLAGS}"
      export NIX_LDFLAGS_FOR_TARGET_UNFILTERED="''${NIX_LDFLAGS_FOR_TARGET_UNFILTERED-$NIX_LDFLAGS_FOR_TARGET}"
      export NIX_LDFLAGS="$(_filter_native_ldflags "$NIX_LDFLAGS")"
      export NIX_LDFLAGS_FOR_TARGET="$(_filter_native_ldflags "$NIX_LDFLAGS_FOR_TARGET")"
    '');

}
