# Cross-compilation support: the per-target modules, and the shell hook
# both of them need.
#
# The per-target wrapper scripts (`wasm32-unknown-wasi ghc --version`) are
# generated by each driver rather than here, since they are built from the
# driver's own cross compilers.

{ config, lib, pkgs, ... }:

let crossPlatform = import ../../libs/cross-platform.nix { inherit lib; };

    selectedCrossPlatforms = config.shell.crossPlatforms (crossPlatform.probe pkgs);

    platformConfigs = map
      (name: pkgs.pkgsCross.${name}.stdenv.hostPlatform.config)
      selectedCrossPlatforms;

    prefixes = lib.filter (p: p != "") platformConfigs;

    targetPrefixes =
      prefixes ++ lib.optional (builtins.any (p: lib.hasInfix "wasm" p) prefixes) "wasm";

    prefixPattern = lib.concatMapStringsSep "|" (p: "*${p}*") targetPrefixes;

    nativeLdflagsHook = ''
      _filter_native_ldflags() {
        local result=""
        for arg in $1; do
          if [[ "$arg" == -L* ]]; then
            case "$arg" in
              ${prefixPattern}) ;;
              *) result="$result $arg" ;;
            esac
          else
            result="$result $arg"
          fi
        done
        echo "$result"
      }

      # Capture the unfiltered flags only once. Re-evaluating the hook in the
      # same shell must not overwrite them with the already-filtered values, or
      # the wrapper below ends up filtering a filtered list and keeps nothing.
      # `-` rather than `:-`, so a genuinely empty capture is preserved.
      export NIX_LDFLAGS_UNFILTERED="''${NIX_LDFLAGS_UNFILTERED-$NIX_LDFLAGS}"
      export NIX_LDFLAGS_FOR_TARGET_UNFILTERED="''${NIX_LDFLAGS_FOR_TARGET_UNFILTERED-$NIX_LDFLAGS_FOR_TARGET}"
      export NIX_LDFLAGS="$(_filter_native_ldflags "$NIX_LDFLAGS")"
      export NIX_LDFLAGS_FOR_TARGET="$(_filter_native_ldflags "$NIX_LDFLAGS_FOR_TARGET")"
    '';

in {

  imports = [
    ./ghcjs
    ./wasm
  ];

  # A shell that selects cross targets carries both native and
  # cross-compiled dependencies, so NIX_LDFLAGS names library directories
  # for both. Handing a native shared object to a cross linker fails on the
  # file type, and the reverse fails just as well, so each side gets only
  # its own. This hook drops the paths of every selected target, and a
  # cross wrapper keeps only those. The unfiltered values stay in the
  # environment for the wrappers to start from.
  shell.shellHook = lib.mkIf (selectedCrossPlatforms != []) nativeLdflagsHook;

}
